version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: [
      "./main",
      "-db-host=db",
      "-db-user=postgres",
      "-db-password=your_password",
      "-db-name=your_dbname",
      "-db-port=5432"
    ]

volumes:
  postgres_data:
